# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const KEY_NAME = "KEY_NAME"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_LANGUAGESELECT = "KEY_LANGUAGESELECT"
const KEY_BACK = "KEY_BACK"
const KEY_QUIT = "KEY_QUIT"
const KEY_TEXT = "KEY_TEXT"
const KEY_PLAY_VIDEO = "KEY_PLAY_VIDEO"
const KEY_PLACEHOLDER = "KEY_PLACEHOLDER"
const KEY_VALUE = "KEY_VALUE"
const KEY_APPLY = "KEY_APPLY"
const TIME_EXECUTION_TEXT = "TIME_EXECUTION_TEXT"
const TIME_EXTRACT_TEXT = "TIME_EXTRACT_TEXT"
const MINER_SELECT_RECIPE = "MINER_SELECT_RECIPE"
const MINER_DISCRIPTION = "MINER_DISCRIPTION"
const UPGRADE_LOCK_TEXT = "UPGRADE_LOCK_TEXT"
const UPGRADE_DISCRIPTION_DROP_PER_CLICK = "UPGRADE_DISCRIPTION_DROP_PER_CLICK"
const UPGRADE_NAME_UNLOCK_WORLD = "UPGRADE_NAME_UNLOCK WORLD"
const UPGRADE_NAME_UNLOCK_RECYCLE = "UPGRADE_NAME_UNLOCK_RECYCLE"
const UPGRADE_DISCRIPTION_UNLOCK_WORLD = "UPGRADE_DISCRIPTION_UNLOCK WORLD"
const UPGRADE_DISCRIPTION_UNLOCK_RECYCLE = "UPGRADE_DISCRIPTION_UNLOCK_RECYCLE"
const UPGRADE_NAME_MINIMG_SPEED = "UPGRADE_NAME_MINIMG_SPEED"
const UPGRADE_NAME_MINIMG_REWARD = "UPGRADE_NAME_MINIMG_REWARD"
const UPGRADE_DISCRIPTION_MINIMG_REWARD = "UPGRADE_DISCRIPTION_MINIMG_REWARD"
const UPGRADE_DISCRIPTION_MINIMG_SPEED = "UPGRADE_DISCRIPTION_MINIMG_SPEED"
const UPGRADE_NAME_DROP_PER_CLICK = "UPGRADE_NAME_DROP_PER_CLICK"
const UPGRADE_NAME_CREATE_PART_WORLD = "UPGRADE_NAME_CREATE_PART_WORLD"
const UPGRADE_DISCRIPTION_CREATE_PART_WORLD = "UPGRADE_DISCRIPTION_CREATE_PART_WORLD"
const MINER_NAME_00 = "MINER_NAME_00"
const MINER_NAME_01 = "MINER_NAME_01"
const MINER_NAME_02 = "MINER_NAME_02"
const MINER_NAME_03 = "MINER_NAME_03"
const MINER_NAME_04 = "MINER_NAME_04"
const MINER_NAME_05 = "MINER_NAME_05"
const MINER_NAME_06 = "MINER_NAME_06"
const MINER_NAME_07 = "MINER_NAME_07"
const MINER_NAME_08 = "MINER_NAME_08"
const MINER_NAME_09 = "MINER_NAME_09"
const MINER_NAME_10 = "MINER_NAME_10"
const MINER_NAME_11 = "MINER_NAME_11"
const MINER_NAME_12 = "MINER_NAME_12"
const MINER_NAME_13 = "MINER_NAME_13"
const MINER_NAME_14 = "MINER_NAME_14"
const MINER_NAME_15 = "MINER_NAME_15"
const MINER_NAME_16 = "MINER_NAME_16"
const MINER_NAME_17 = "MINER_NAME_17"
const MINER_NAME_18 = "MINER_NAME_18"
const MINER_NAME_19 = "MINER_NAME_19"
const MINER_NAME_20 = "MINER_NAME_20"
const MINER_NAME_21 = "MINER_NAME_21"
const MINER_NAME_22 = "MINER_NAME_22"
const MINER_NAME_23 = "MINER_NAME_23"
const MINER_NAME_24 = "MINER_NAME_24"
const MINER_NAME_25 = "MINER_NAME_25"
const MINER_NAME_26 = "MINER_NAME_26"
const MINER_NAME_27 = "MINER_NAME_27"
const MINER_NAME_28 = "MINER_NAME_28"
const MINER_NAME_29 = "MINER_NAME_29"
const MINER_NAME_30 = "MINER_NAME_30"
const MINER_NAME_31 = "MINER_NAME_31"
const MINER_NAME_32 = "MINER_NAME_32"
const MINER_NAME_33 = "MINER_NAME_33"
const MINER_NAME_34 = "MINER_NAME_34"
const SAVE_PROGRESS_TEXT = "SAVE_PROGRESS_TEXT"
const STOP_MINER_TEXT = "STOP_MINER_TEXT"
const BUTTON_TEXT_BUY = "BUTTON_TEXT_BUY"
const BUTTON_TEXT_SELECTE = "BUTTON_TEXT_SELECTE"
const BUTTON_TEXT_CANSEL = "BUTTON_TEXT_CANSEL"
const BUTTON_TEXT_MAX = "BUTTON_TEXT_MAX"
const BUTTON_TEXT_LOCK = "BUTTON_TEXT_LOCK"
const BUTTON_TEXT_SELECTE_RECIPE = "BUTTON_TEXT_SELECTE_RECIPE"
const BUTTON_TEXT_CHANGE_RECIPE = "BUTTON_TEXT_CHANGE_RECIPE"
const TEXT_CLICK_TO_RECYCLE = "TEXT_CLICK_TO_RECYCLE"

const KEYS = [
 "KEY_NAME",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_LANGUAGESELECT",
 "KEY_BACK",
 "KEY_QUIT",
 "KEY_TEXT",
 "KEY_PLAY_VIDEO",
 "KEY_PLACEHOLDER",
 "KEY_VALUE",
 "KEY_APPLY",
 "TIME_EXECUTION_TEXT",
 "TIME_EXTRACT_TEXT",
 "MINER_SELECT_RECIPE",
 "MINER_DISCRIPTION",
 "UPGRADE_LOCK_TEXT",
 "UPGRADE_DISCRIPTION_DROP_PER_CLICK",
 "UPGRADE_NAME_UNLOCK WORLD",
 "UPGRADE_NAME_UNLOCK_RECYCLE",
 "UPGRADE_DISCRIPTION_UNLOCK WORLD",
 "UPGRADE_DISCRIPTION_UNLOCK_RECYCLE",
 "UPGRADE_NAME_MINIMG_SPEED",
 "UPGRADE_NAME_MINIMG_REWARD",
 "UPGRADE_DISCRIPTION_MINIMG_REWARD",
 "UPGRADE_DISCRIPTION_MINIMG_SPEED",
 "UPGRADE_NAME_DROP_PER_CLICK",
 "UPGRADE_NAME_CREATE_PART_WORLD",
 "UPGRADE_DISCRIPTION_CREATE_PART_WORLD",
 "MINER_NAME_00",
 "MINER_NAME_01",
 "MINER_NAME_02",
 "MINER_NAME_03",
 "MINER_NAME_04",
 "MINER_NAME_05",
 "MINER_NAME_06",
 "MINER_NAME_07",
 "MINER_NAME_08",
 "MINER_NAME_09",
 "MINER_NAME_10",
 "MINER_NAME_11",
 "MINER_NAME_12",
 "MINER_NAME_13",
 "MINER_NAME_14",
 "MINER_NAME_15",
 "MINER_NAME_16",
 "MINER_NAME_17",
 "MINER_NAME_18",
 "MINER_NAME_19",
 "MINER_NAME_20",
 "MINER_NAME_21",
 "MINER_NAME_22",
 "MINER_NAME_23",
 "MINER_NAME_24",
 "MINER_NAME_25",
 "MINER_NAME_26",
 "MINER_NAME_27",
 "MINER_NAME_28",
 "MINER_NAME_29",
 "MINER_NAME_30",
 "MINER_NAME_31",
 "MINER_NAME_32",
 "MINER_NAME_33",
 "MINER_NAME_34",
 "SAVE_PROGRESS_TEXT",
 "STOP_MINER_TEXT",
 "BUTTON_TEXT_BUY",
 "BUTTON_TEXT_SELECTE",
 "BUTTON_TEXT_CANSEL",
 "BUTTON_TEXT_MAX",
 "BUTTON_TEXT_LOCK",
 "BUTTON_TEXT_SELECTE_RECIPE",
 "BUTTON_TEXT_CHANGE_RECIPE",
 "TEXT_CLICK_TO_RECYCLE"
]